### ISSUE TITLE
Feedback from Sivakorn (Oak) Chongfeungprinya

### ISSUE THREAD

**Issue by sivakornchong** [UBC-MDS/DSCI-532_2024_16_SilentEpidemic#107]
Feedback

Overall, this dashboard is at production quality and it is already more than sufficient. I find it hard to believe this is done in 3 weeks.

1. Is the app overall well-suited to the usage scenario and target audience?

The usage of this app is identified to be as teaching tool for high school students in California. Thinking as a teacher, I will say that this dashboard does well to reflect the issues of increasing drug uses. I like that there is one large main charts showing 'Overdoses Deaths and Death Rates by Drug Type', and that the default setting is to show all drugs uses. This will allow the teacher to emphasize the epidemic is not just for one drug, but all. 

One minor suggestion would be to identify what Fold Change mean for the top right corner box. 

2. Do you see some ways that the dashboard could be extended to better cater to the target audience or meet the specifications in the usage scenario?

A minor suggestion would be to have a legend showing sizes of bubbles against death rates for the main chart. Even though a teacher may be able to interact with the chart, students may just be able to view the charts, and would not know what each size of bubbles corresponds to.

3. Was the app intuitive to use? Did it behave as you expected?

I think the dashboard is quite intuitive to use. All charts timeline and drug selection moves as per expected.  I like that there is a clear description on what the dashboard is doing at the bottom right corner too. Charts are well labelled and easy to use. 

When making selection on gender, I was expecting all charts to change based on aggregation, but the bottom right chart doesn't. It will be good to indicate that the bottom right chart is for both genders and all age groups. 

4. Can you think of other alternatives or improvements for the plots regarding the selection of the plots or how they are set up to reach to the widgets?

For this chart, 'Overdose Death Rate based on Demographic', the bars are quite small and difficult to see especially if all drugs are selected. 

5. Aesthetics comment

Some minor aesthetics comment: to me the red big fonts jump out slightly too much when compared to pastel colors in the charts. Other that that, I find the dashboard visually pleasing. 

Excellent work team!

**Comment by SoloSynth1** [comment]
Thanks for the feedback @sivakornchong! We've addressed the points that you have raised. Please refer to the linked issues. I will now close this issue as there is no more action items left to be done, but please feel free to re-open it again in the case you have further feedback or something is still not addressed. Thanks again!
