### ISSUE TITLE
Feedback from Sifan

### ISSUE THREAD

**Issue by sifanzzz** [UBC-MDS/DSCI-532_2024_16_SilentEpidemic#108]
Your dashboard is very well-designed, structured and presented. I am especially impressed by the overview area in red font that works as an emphasis of the data. Overall great work! Here are some suggestions:

- For the bubble chart(Overdoses Deaths and Death Rates by Drug Type):

The size of the bubbles represents the number of deaths, which provides an intuitive visual representation of the number of deaths compared between different drugs. There are many data points in the bubble chart, which can feel overly complicated, especially when I select all the drug types.

- For the line chart (Percentage of Overdose Deaths Involving Opioids as a Secondary Factor)

It shows the percentage of overdose deaths caused by opioids as a secondary factor, broken down by drug type and sex. The colours look nice, but it can also be too complex when all the drug types and both genders are selected. The lines seem to overlap with each other. Would it be better if you separate the data by gender into two graphs?

- For the bar chart (Overdose Death Rate based on Demographic)

This chart is small but has lots of information. If the data for every demographic group is displayed in one chart, it can seem overcrowded. Since the bar is too dense, it is hard to read the data even with hovering display. Consider allowing users to interactively choose to view data for specific groups.

Overall, the dashboard is informative and designed to be fairly clear, allowing people to quickly grasp key data. However, every chart can take some time to read because it contains a large number of data points. At the same time, multiple charts of different colours and shapes may also take a while to distinguish and understand.

**Comment by SoloSynth1** [comment]
Thanks for the feedback @sifanzzz! We've addressed the points that you have raised. Please refer to the linked issues. I will now close this issue as there is no more action items left to be done, but please feel free to re-open it again in the case you have further feedback or something is still not addressed. Thanks again!
