### ISSUE TITLE
reports/m1_proposal.md - Section 2: Description of the data

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/DSCI-532_2024_16_SilentEpidemic#12]
rubric={reasoning:12}

You are allowed to select any dataset you want for this project, as long as you have the license to use it publicly. Finding a suitable data set can take a lot of time and effort. You are therefore allowed to select one that you have worked with in a previous lab/project in MDS if you wish.

A few datasets that have been popular in previous years:

https://www.kaggle.com/zynicide/wine-reviews/data
https://github.com/themarshallproject/city-crime
https://archive.ics.uci.edu/dataset/45/heart+disease
Good general resources for finding interesting datasets:

https://github.com/fivethirtyeight/data
https://github.com/the-pudding/data
https://www.kaggle.com/datasets
https://ourworldindata.org/teaching#how-can-i-use-our-world-in-data-to-teach
https://opendata.vancouver.ca/
https://archive.ics.uci.edu/
In your proposal, briefly describe the dataset and the variables that you will visualize:

Include how many rows and columns there are in the dataset (that you plan to use).
There should be a clear link to how the dataset and the variables you describe will help you solve your target audience's problem.
Indicate at least one new variable that you are planning to derive/engineer for your visualizations.
If there are no new variables to derive, indicate what additional information you would have liked to have in the dataset to better be able to answer your research questions (even if it is impossible for you to engineer it).
If you are planning to visualize a lot of columns, provide a high level description of the variable types rather than listing every single column.
For example, indicate that the dataset contains a variety of categorical variables for demographics and provide a brief list rather than describing every single variable.
You may also want to consider visualizing a smaller set of variables given the short duration of this project.
To be able to include this information you might wish to perform a brief exploratory data analysis for you to grasp what could be interesting variables to look at in your data. We will not be grading the EDA aspect, but include your EDA notebooks in the public GitHub repo, so that you have everything in one place.

Example writeup:

We will be visualizing a dataset of approximately 300,000 missed patient appointments. Each appointment has 15 associated variables that describe the following characteristics, which we hypothesize could be helpful in determining why patient's miss their appointments:

Patient demographics (patient_id, gender, age, etc)
The health status of the patient (general_health_status, existing_conditions e.g. "Hypertension", "Physical disability")
Information about the appointment itself (appointment_id, appointment_date)
Whether the patient received a reminder about the appointment (reminder_sent)
Whether the patient showed up (status)
Using this data we will also derive new variables, such as the time since the patient's last appointment (days_since_last_appointment) and which weekday the appointment was on (appointment_weekday), as it would be interesting to explore if these could be linked to the patient missing their appointment.

Another example of [a good description of a dataset is the Kaggle world happiness report](https://www.kaggle.com/unsdsn/world-happiness).

**Comment by jinyz8888** [comment]
The dataset we will be visualizing concerns the National Drug Overdose (OD) Deaths spanning from 1999 to 2021, sourced from the CDC WONDER database. The variables within this dataset are categorized into several key groups:

1. Overall OD Death Counts and Rates: We will examine the total number of drug overdose deaths and the rate of these deaths per 100,000 population. This rate is age-adjusted to account for the different age distributions within the population.
This dataset includes around 204 rows and 24 columns. 

2. Age-Specific OD Data: Focusing on the 15-24 age group, we will look at both the number and rate of drug overdose deaths. This age specification allows us to analyze trends among younger individuals, which can be pivotal for early intervention strategies. This dataset includes around 130 rows and 24 columns.

3. Demographic-Specific OD Rates: The dataset provides overdose death rates broken down by demographic variables. These rates are also age-adjusted per 100,000 population, allowing for comparison across different demographic groups without the influence of age distribution. This dataset includes around 83 rows and 24 columns.

The variables are helpful in visualization are:
- year (from 1999 to 2021)
- sex (Female, Male)
- prescription and illicit drugs (Any Opioid, Prescription Opioids, Heroin, Synthetic Opioids other than Methadone (primarily fentanyl), Stimulants, Cocaine, etc.)

Our visualizations will emphasize trends and patterns that could inform healthcare providers, policymakers, and community leaders about the critical aspects and changes in drug overdose deaths, with the aim to support efforts in prevention and intervention.

**Comment by jinyz8888** [comment]
Two questions:
1. A clear link to how the dataset and the variables you describe will help you solve your target audience's problem? 
2. Do we need a new variable?

**Comment by AlysenTownsley** [comment]
For 2. we could engineer a new feature called the proportion of deaths by each drug type (calculate the number of deaths in each drug type and divide it by the total deaths) to find the most "deadly" drug.

**Comment by jinyz8888** [comment]
Great point! Thanks!

**Comment by jinyz8888** [comment]
Update version:

# Section 2: Description of the Data
In response to Dr. Darling's concern and NIDA's commitment to addressing the surge in drug overdose fatalities, We will visualize data on National Drug Overdose Deaths from 1999 to 2021, drawn from the CDC WONDER database. The dataset provides detailed information on overdose deaths across the United States, categorized by drug type and demographic variables, and is a rich resource for understanding the evolving landscape of drug overdose fatalities.

Key components of the dataset include:

1. Overall Overdose Death Counts and Rates: The total counts of drug overdose deaths are presented alongside age-adjusted rates per 100,000 population, highlighting the escalation in drug overdose deaths, to stress the urgency of informed preventative education. The age-adjusted mortality rates per 100,000 population facilitate a comparative analysis over time, despite demographic shifts. This dataset contains approximately 204 rows and 24 columns.

2. Age-Specific Overdose Data: Specifically targeting the 15-24 age demographic, the data offer insights into overdose deaths within this younger cohort, crucial for informing early prevention and educational initiatives. This subset includes around 130 rows and 24 columns.

3. Demographic-Specific Overdose Rates: Further, the dataset breaks down overdose death rates by demographic categories such as gender and ethnicity, age-adjusted per 100,000 population, ensuring our dashboard is tailored to addresss specific educational needs. It includes approximately 83 rows and 24 columns.

The primary variables that will drive our visual analysis include:

- Year: Temporal variable to illustrate time patterns, spanning from 1999 to 2021
- Gender: Categorical variable to draw out disparities in drug misuse impacts between males and females.
- Drug Categories: Categorical variable to elucidate the differential dangers they pose, including Any Opioid, Prescription Opioids, Heroin, Synthetic Opioids (other than Methadone, primarily fentanyl), Stimulants, Cocaine, and others.

A new variable, the 'Proportion of Deaths by Drug Type,' will be introduced to ascertain the most lethal drugs by taking the number of deaths attributable to each drug type and dividing it by the total number of overdose deaths. This metric will allow us to emphasize the disproportionate danger of certain substances, such as fentanyl, in our educational outreach.

Ideally, we would also have data on the educational backgrounds of individuals who succumbed to overdoses to directly link educational interventions to potential reductions in mortality rates. Although we can't engineer this from the available data, it would provide a more concrete foundation for our program's impact assessment.

Our visualizations aim to shed light on trends and changes in drug overdose deaths over the years. This crucial information directly addresses the concerns of our audience and aid healthcare professionals, policymakers, educators, and community leaders in developing targeted interventions and educational programs to prevent drug misuse and overdose, especially among youth, thereby aligning with NIDA's mission and Dr. Darling's objectives for the California State Board of Education.
