### ISSUE TITLE
Filtering demo chart

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/DSCI-532_2024_16_SilentEpidemic#125]
Related to #86.
> - The barplot that segments overdose death rates based on demographics could have a selection filter, for the user to select a certain demographic and see the overdose death rates across years for all drug types. This filter could also be linked to the other plots, to show deaths and overdoses for specific drugs for a certain demographic.

**Comment by billwan96** [comment]
> - The barplot that segments overdose death rates based on demographics could have a selection filter, for the user to select a certain demographic and see the overdose death rates across years for all drug types. This filter could also be linked to the other plots, to show deaths and overdoses for specific drugs for a certain demographic.

This should be the correct part of Waleed's feedback

**Comment by billwan96** [comment]
As discussed the filter on the demographic is supported with plotly. (i.e. clicking on the legend would do the filtering)

**Comment by SoloSynth1** [comment]
Yeah thanks @billwan96 I didn't notice I copied the wrong paragraph
