### ISSUE TITLE
Feedback from Joel M4

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_16_SilentEpidemic#135]
Implement eight minor

Major:

None

Minor:

- [x] Figure out legend for line chart. Dotted vs solid
- [x] Match color of main bubble chart with line chart in terms of the individual drug types
- [x] 6.3x
- [x] Either make dropdown not clearable or have a placeholder for charts that says "please make a selection"
- [x] #163
- [x] Change bottom bar line chart to line chart
- [x] Indicate for bottom right chart is not dependent on all filters
- [x] Fix overlap in max slider values
- [x] Don't have a subtitle for what is in the legend
- [x] Make range slider have a minimum of at least two years or have a placeholder
- [x] Fix deathrates calculation

**Comment by SoloSynth1** [comment]
Might have duplicates with existing issues, will link related issues to here tmr.

**Comment by SoloSynth1** [comment]
Thanks for the feedback @joelostblom! We've addressed the points that you have raised. Please refer to the linked issues. I will now close this issue as there is no more action items left to be done, but please feel free to re-open it again in the case you have further feedback or something is still not addressed. Thanks again!
