### ISSUE TITLE
Update the "About" section in your repo

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/DSCI-532_2024_16_SilentEpidemic#38]
Update the "About" section in your repo (the panel to the right on the repo home page) by clicking on the gear/cogwheel:
- Include a one-sentence description of your project in the "Description" field.
- Include the link to your deployed dashboard in the "Website" field.
- Include ~3-5 keywords in the "Topics" field. For this project, these keywords should be related to the dashboard components and visualizations you are including, e.g. "slider", "dropdown", "map", etc.

**Comment by SoloSynth1** [comment]
About section updated:

<img width="650" alt="image" src="https://github.com/UBC-MDS/DSCI-532_2024_16_SilentEpidemic/assets/17952490/2ba6b19f-dfdd-487d-9133-f9fd7062f8ec">

@AlysenTownsley @billwan96 @jinyz8888 If this looks OK to you then let's close this issue.

**Comment by billwan96** [comment]
Not sure why it takes forever for me to load the page....

**Comment by SoloSynth1** [comment]
Yeah prob the deploy pipeline is not working, looking into the issue

**Comment by SoloSynth1** [comment]
Oh, I forgot the whole thing needs to be manually deployed and didn't push the deploy button last night. Now it should be working fine. Sorry about that!

**Comment by billwan96** [comment]
yup it works, thanks @SoloSynth1
