### ISSUE TITLE
Ensure the interface is self-documenting

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/DSCI-532_2024_16_SilentEpidemic#51]
Your interface should be as self-documenting as possible, with:
- [ ] appropriate labels for panes and widgets
- [x] an overall title for the dashboard

**Comment by SoloSynth1** [comment]
@billwan96 @AlysenTownsley @jinyz8888 Any comments on "appropriate labels for panes and widgets"?

**Comment by SoloSynth1** [comment]
One thing I can think of is that the "Last Updated" time is currently showing the date in UTC+0. To prevent confusion, either we need to add a call to transform it to Pacific Time or to show Zulu time.

**Comment by billwan96** [comment]
I was also thinking should we add a note on demographic plot wont change with selection of youth and gender

**Comment by SoloSynth1** [comment]
The filter rows in sidebar could be more spaced. Let's see if there is time for that.

**Comment by SoloSynth1** [comment]
Not enough time. Removing this from Milestone 2 and saving this for next week.

**Comment by jinyz8888** [comment]
How about "United States Drug Overdose Analysis (1999-2021)"?

**Comment by SoloSynth1** [comment]
> How about "United States Drug Overdose Analysis (1999-2021)"?

So far we haven't received related feedback on this, which I assume the interface is self-documenting enough for everyone to be OK with it.

Closing this issue.
