### ISSUE TITLE
Feedback from Joel

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_16_SilentEpidemic#74]
Major:
- [x] Think about how to distinguish men/women. Line solid/dotted? No line + different shading of points?
- [x] Why is axis not the same for all plots when "Any opoid" checked? Double counting?
- [x] Theme with all colors in the dashboard

Minor:
- [x] Legends?
- [x] Indicate that size is the death rate
- [x] Multidropdown instead of multiselect
- [x] Male + Female check instead of drop
- [x] Take away "any opiod"
- [x] Align numbers in cards
- [x] Red color in cards?
- [x] Title in horizontal?
- [x] Navbar?

**Comment by SoloSynth1** [comment]
Closing this issue as all tasks were done/addressed.
