### ISSUE TITLE
Add year range information at the top right corner

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/DSCI-532_2024_16_SilentEpidemic#79]

**Comment by SoloSynth1** [comment]
Not sure if adding this would be the best, this looks very redundant:

<img width="1266" alt="image" src="https://github.com/UBC-MDS/DSCI-532_2024_16_SilentEpidemic/assets/17952490/7d4ef6fb-2b66-44ba-861a-d5316a31861f">

**Comment by SoloSynth1** [comment]
Aligning to the right does not look good either. I don't like it being very verbose and wordy
<img width="1478" alt="image" src="https://github.com/UBC-MDS/DSCI-532_2024_16_SilentEpidemic/assets/17952490/11ea8397-2d43-403e-a174-7447f2eb2ae1">

**Comment by SoloSynth1** [comment]
@jinyz8888 @billwan96 @AlysenTownsley I need your input. Do you think implementing this is still a good idea especially now the filters are well-separated and the year range is clearly visible?

**Comment by jinyz8888** [comment]
@SoloSynth1 Yeah, I agree with you. It is wordy and we don't need to repeat the information in the filter.

**Comment by SoloSynth1** [comment]
Thanks @jinyz8888, closing this issue for now.
