### ISSUE TITLE
Feedback from Waleed

### ISSUE THREAD

**Issue by WaleedMahmood1** [UBC-MDS/DSCI-532_2024_16_SilentEpidemic#86]
The dashboard overall is functional and easy-to-use. Well done!

### Some feedback:
Is the app overall well-suited to the usage scenario and target audience?

- The overall dashboard seems to be well-suited to the usage scenario and target audience as it seems to contain the necessary information required for the target audience to become more aware on the increasing rates of drug overdose deaths.

Do you see some ways that the dashboard could be extended to better cater to the target audience or meet the specifications in the usage scenario?

- I think that the card displaying the Average death rate could have a more informative title. At the initial look, it is a little bit confusing as to what the average death rate is for, i.e. is it the average proportion of deaths among all users, or deaths among those who overdosed? A bit more exploration from the dropdowns helps clear it up. Because it is a figure that would clearly illustrate the chance of a user facing death by drug overdose, it should be as clearly understood as possible by the target audience.
- A fold change might be too complicated a figure for raising awareness among high school students.

Was the app intuitive to use? Did it behave as you expected?

- I think the dashboard is intuitive to use.
- Since the default selection of `Drug Type` is each box selected, it is a bit tedious to unselect all when I only want to view the stats for one drug. A good idea might be to have the default value be one box selected that is labelled as `All Drugs` and is set to link to all drug types in backend and then the rest of the individual drugs are unselected. 

Can you think of other alternatives or improvements for the plots regarding the selection of the plots or how they are set up to reach to the widgets?

- The color scheme for the drugs could be kept static. Currently, when I unselect a drug type, the colors for each of the rest of the drug types changes and I have to re-view the legend and correspond the data points with it. I felt a bit confused when I removed `Cocaine` from the selection but the color that got removed from the plot was of `Synthetic Opioids`. Perhaps, keeping a consistent color mapping could be explored to make the plots more consistent and lead to less confusion.

- The barplot that segments overdose death rates based on demographics could have a selection filter, for the user to select a certain demographic and see the overdose death rates across years for all drug types. This filter could also be linked to the other plots, to show deaths and overdoses for specific drugs for a certain demographic. 

Are the plots or other outputs sufficiently described / intuitive enough for the target audience?

- The plots seem intuitive enough for the audience to interpret.

**Comment by SoloSynth1** [comment]
Thanks for the feedback @WaleedMahmood1! We've addressed the points that you have raised. Please refer to the linked issues. I will now close this issue as there is no more action items left to be done, but please feel free to re-open it again in the case you have further feedback or something is still not addressed. Thanks again!
