### ISSUE TITLE
Feedback from Jake

### ISSUE THREAD

**Issue by jbarns14** [UBC-MDS/DSCI-532_2024_16_SilentEpidemic#88]
The dashboard looks great! Well done guys!

Overall, the dashboard presents very smoothly and professionally. It was tough to find potential suggestions but here is my feedback:

- Creating the virtual environment was a little tough because I've never used venv before. I think it may be helpful to include a step in the instructions to tell people to install virtualenv using 'pip install virtualenv'. 
- The main chart is a great visualization of deaths by drug type. However, it is difficult to control the tooltip in the crowded parts of the graph as many of the bubbles overlap with each other. It may be worth considering trying to spread them out a bit (perhaps by using a different scale on the y-axis, if feasible).
- It may be helpful to include a 'reset selections' button to help users reset their filter choices so they can smoothly start a new query. Alternatively you could consider a clear all selections button. This would be useful as currently users need to unclick each drug if they only want to see one or two in the plot.
- Finally, I see that you have an environment.yml file. It may be worth adding the instructions to create a conda environment to give that option to those who are more comfortable with conda.

Overall, the dashboard is very impressive! Keep up the great work Group 16!

Jake

**Comment by SoloSynth1** [comment]
Thanks for the feedback @jbarns14! We've addressed the points that you have raised. Please refer to the linked issues. I will now close this issue as there is no more action items left to be done, but please feel free to re-open it again in the case you have further feedback or something is still not addressed. Thanks again!
